### PR TITLE
fix(fabric): prevent freeze on layout update during transition

### LINKED ISSUE #922: (iOS) `setPage` calls with container layout changes cause the content to freeze
## Environment

react-native-pager-view version 6.3.0, 6.5.1

I initially noticed this bug in my app on a real device, and it didn’t reproduce on the simulator.
However, with the example app, it was reproduced on both a real device and the simulator.

<details><summary>my local dev environment</summary>
<p>

```
System:
  OS: macOS 15.1
  CPU: (8) arm64 Apple M1 Pro
  Memory: 112.80 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.11.1
    path: ~/.nvm/versions/node/v20.11.1/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.11.1/bin/yarn
  npm:
    version: 10.2.4
    path: ~/.nvm/versions/node/v20.11.1/bin/npm
  Watchman:
    version: 2024.11.04.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/floydkim/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 24.1
      - iOS 18.1
      - macOS 15.1
      - tvOS 18.1
      - visionOS 2.1
      - watchOS 11.1
  Android SDK:
    API Levels:
      - "34"
      - "35"
    Build Tools:
      - 33.0.0
      - 33.0.1
      - 34.0.0
      - 35.0.0
    System Images:
      - android-34 | Google APIs ARM 64 v8a
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.1 AI-241.18034.62.2412.12266719
  Xcode:
    version: 16.1/16B40
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /Users/floydkim/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: true
  newArchEnabled: false

```

</p>
</details> 

## Description

This issue occurs when using `setPage` in pager-view to navigate pages with animation.
If the layout size (e.g., height) of the pager-view component changes, content becomes uncontrollable within the pager-view, and further page navigation becomes impossible.

The issue does not occur when using the `setPageWithoutAnimation` method.
Additionally, I found that if the width and height of the pager-view are fixed, this issue does not occur.

It seems that the iOS native UI component might break due to container layout changes—just a shallow guess.

### Video (iPhone 15 real device)

1. Build the example app.
2. Go to the `Keyboard Example` menu.
3. Touch the TextInput to show the keyboard.
4. Press the `Next` page button.
5. Then you can’t interact with anything inside the pager-view or navigate to the previous page. However, you can still exit the navigation screen.

https://github.com/user-attachments/assets/e3c3a6d3-5531-4c93-9b8a-cb359104be2d

## Reproducible Demo

The reproduction code is based on the library’s example app. ([link](https://github.com/floydkim/react-native-pager-view/tree/reproducer/example))
It is almost the same as the example app code.

The keyboard interaction is an indirect cause; it was used because it easily triggers view height changes.

### PR DESCRIPTION
**Pull request by krozniata**
# Summary

This PR fixes issue causing component to freeze when layout was updated during transition

When layout was updated e.g. because of hiding keyboard, `setViewControllers` completion block was never called, which resulted in swipe being disabled

It fixes this issue by preventing layout update during transition phase and updating it after transition ends

## Test Plan

1. Build the example app.
2. Go to the Keyboard Example menu.
3. Touch the TextInput to show the keyboard.
4. Press the `Next` page button. (might be required to modify `ControlPanel` to move button above keyboard)
6. Should navigate correctly, should be able to interact

Other examples should work as before

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

### CODE REVIEW

**Review by MrRefactor — APPROVED** [review]
LGTM, is that issue Fabric only?

**Comment by floydkim** [comment]
Thank you for fixing the issue so quickly.

@MrRefactor this problem also occurs on Paper.
My bad. I didn’t include it in the issue description but only mentioned it as a commit message in my reproducer code.

**Comment by troZee** [comment]
@floydkim could you test that fix on your end ?

**Comment by floydkim** [comment]
@troZee Sure, but my app runs on Paper, so I can’t apply this fix directly. Instead, I’ll test it with the example app.

**Comment by floydkim** [comment]
tested on `fix/layout-freeze` branch

Issue has been resolved on Fabric.

<table>
  <tr>
    <th>Paper</th>
    <th>Fabric (Sim.)</th>
    <th>Fabric (real device)</th>
  </tr>
  <tr>
<td>
      <video src="https://github.com/user-attachments/assets/2032c6a0-9070-482c-a381-e9a757ad8e1e" width=300 />
</td>
<td>
      <video src="https://github.com/user-attachments/assets/2bd2767a-e91d-4db2-80dd-676857412b78" width=300 />
</td>
<td>
      <video src="https://github.com/user-attachments/assets/02dfbe1d-7a99-45e2-9fa4-e1dbb382790a" width=300 />
</td>
  </tr>
</table>

**Pull request merged**
