### PR TITLE
fix(ios): onScroll callback values

### PR DESCRIPTION
**Pull request by troZee**
# Summary

Close https://github.com/callstack/react-native-pager-view/issues/421

The native component does not handle a such case, where user can scroll to n page, where n > 1. To fix this issue, I used workaround and call `setPage` method for each page, which should be displayed 

eg. 
current index:0 
next index: 4 
call setPage(1)...setPage(4)

This fix unifies the behaviour for both platforms. 

## Test Plan

* Go to OnPageScroll Example 
* Play with tabs

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅   |
| Android |    ❌     |

## Video 

https://user-images.githubusercontent.com/12766071/132377263-6f201f62-c836-4441-ba34-f95370b08baa.mov

### CODE REVIEW

**Review by satya164 — APPROVED** [review]

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.2

**Comment by sbin1211** [comment]
@troZee i don't think it fixed the problem completely, as it trigger onPageSelected incorrect. 
i tried react-native-tab-view which using react-native-pager-view.  the onIndexChange Method trigger with wrong index.

**Comment by troZee** [comment]
> @troZee i don't think it fixed the problem completely, as it trigger onPageSelected incorrect.
> i tried react-native-tab-view which using react-native-pager-view. the onIndexChange Method trigger with wrong index.

Could you provide a more details in a separate task ?

**Comment by sbin1211** [comment]
https://user-images.githubusercontent.com/22540308/133788949-e51b4708-f383-4157-ba38-e236c1cdb4dc.mp4

@troZee check the video.
1. trigger onPageSelected multiple times,
2. page index is wrong.

**Comment by troZee** [comment]
@sbin1211 thank you for recording a video. I have created a separate issue for that problem.

**Comment by troZee** [comment]
@sbin1211 https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.6

**Pull request merged**
