### PR TITLE
Resolve RLT support 

### PR DESCRIPTION
**Pull request by ghoudi01**
resolve rtl support

# Summary

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

### CODE REVIEW

**Comment by theMasix** [comment]
Could you please check this PR ASAP?

@satya164 @troZee 
This bug affects the rtl-based app that has been migrated to`react-navigation@6` or`react-native-tab-view@3`.

Refer to https://github.com/satya164/react-native-tab-view/issues/1266

**Comment by satya164** [comment]
> Could you please check this PR ASAP?

Can you not ping me on the weekend for a 5 hour old PR? If the PR is necessary for you then use patch-package to temporarily use it in your project.

**Comment by theMasix** [comment]
@ghoudi01 
The PR solves the issue of pressing "next tabs". But if you want to press "previous tabs" it doesn't work an previous tabs are untouchable.

**Comment by Hady207** [comment]
Can this PR get Merged, please?

**Comment by ghoudi01** [comment]
any news about the test ?

**Comment by ghoudi01** [comment]
Can this PR get Merged

**Comment by YogiHa** [comment]
+1

**Comment by AhmedHalbas** [comment]
Can this Pull Request be merged?

**Comment by YogiHa** [comment]
Any updates about this issue?

**Comment by react-one** [comment]
i == _currentIndex as like in the block above. Will avoid treating the same page.

**Comment by react-one** [comment]
@ghoudi01 check the above! `i == _currentIndex` as like in the block above. Will avoid treating the same page.

**Review by mouessam — APPROVED** [review]

**Review by MuhmdRaouf — APPROVED** [review]

**Comment by YogiHa** [comment]
Are there's any reason why this PR not merged?

**Comment by RodinHatokayTe** [comment]
there is still problem with this patch when setting the device language to RTL (Hebrew or Arabic )

**Comment by PeterAbdalla** [comment]
Any updates about this issue?

**Comment by m-deacon** [comment]
@satya164, I know you didn't want to be tagged 5 hours after this PR was made, but it's now been 6 months - any update on merging this or why this hasn't been merged yet? Thanks

**Comment by satya164** [comment]
@m-deacon I am not a maintainer of this repo. Please don't tag me.

**Comment by troZee** [comment]
> @satya164, I know you didn't want to be tagged 5 hours after this PR was made, but it's now been 6 months - any update on merging this or why this hasn't been merged yet? Thanks

Hello, 
For now I cannot merge this PR, since it has conflicts. Please provide a proper description and repo steps, then I will be able to check the changes

**Comment by troZee** [comment]
@ghoudi01 will you update your PR ?

**Comment by Roshdy** [comment]
Any update on this thread??

**Comment by omerts** [comment]
@troZee Here is a repo:

```
import React from 'react';
import { I18nManager, StyleSheet, Text, View } from 'react-native';
import PagerView from 'react-native-pager-view';

I18nManager.forceRTL(true)
I18nManager.allowRTL(true)

const App = () => {
  return (
    <PagerView style={styles.pagerView} initialPage={0}>
      <View key='1'>
        <Text>First page</Text>
      </View>
      <View key='2'>
        <Text>Second page</Text>
      </View>
    </PagerView>
  )
}

const styles = StyleSheet.create({
  pagerView: {
    flex: 1,
  },
})

export default App

```

Scroll left to the second page, and then try to scroll back to the right page. It doesn't work. 
This also effects `react-native-tab-view` where you can't go to another tab.

**Comment by troZee** [comment]
> Any update on this thread??

This PR breaks current pager behaviour. Please add a fix without breaking anything

**Comment by sebasg0** [comment]
Hey @troZee https://github.com/callstack/react-native-pager-view/pull/613 raised this pr to properly fix this issue please check and merge is everything looks alright

**Pull request closed without merging**
