### PR TITLE
Render blocks UI thread

### PR DESCRIPTION
**Pull request by alpha0010**
# Summary

The LazyPager render trigger can block UI https://github.com/callstack/react-native-pager-view/issues/104#issuecomment-860518078.  This PR aims to resolve such by changing event scheduling.

### What's required for testing (prerequisites)?

"Lazy Render Example" screen from the example app.

### What are the steps to reproduce (after prerequisites)?

Navigating between pages should work the same as current `next` branch (firing events, mount/unmount pages).  I have not observed the issue locally; maybe @DanijelBojcic can comment?

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

### CODE REVIEW

**Comment by DanijelBojcic** [comment]
Sorry, I was a bit busy this week.
I have tried your implementation, unfortunately its the same.
I have heavy pages in the pager-view, maybe thats why its struggling when rendering.

**Comment by DanijelBojcic** [comment]
I have a fix for this that works for me.

@alpha0010  Can you give me access to your fork? Can't push to it.

**Comment by troZee** [comment]
> I have a fix for this that works for me.
> 
> @alpha0010 Can you give me access to your fork? Can't push to it.

Could you create a separate PR on this repo, which will point to the next branch ? I would like to compare both fixes. Thank you in advance.

**Comment by DanijelBojcic** [comment]
> > I have a fix for this that works for me.
> > @alpha0010 Can you give me access to your fork? Can't push to it.
> 
> Could you create a separate PR on this repo, which will point to the next branch ? I would like to compare both fixes. Thank you in advance.

#380

**Comment by troZee** [comment]
Should I merge it to `next` branch ?

**Comment by DanijelBojcic** [comment]
I remember that my PR does not work in all scenarios, do it should be rejected, and I've stopped using the LazyPager, so I don't know if this PR is still relevant or not.

**Pull request closed without merging**
