### PR TITLE
fix(ios): Prevent removal of one or many pages at a time

### LINKED ISSUE #465: Removing last page when it's active causes a crash in iOS on RN 0.64
## Environment

- react-native: 0.63.4
- react-native-pager-view: 5.4.7

## Description

If we remove the last child of the PagerView, when it's active, iOS crashes with:

```
Exception thrown while executing UI block: *** -[__NSArrayM objectAtIndexedSubscript:]: index 4 beyond bounds [0 .. 3]

__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
    RCTUIManager.m:1199
__44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.496
__RCTExecuteOnMainQueue_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start

```

## Reproducible Demo

This is a minimal case that we can verify this crash happening. A simple app to navigate to the 5th (last) page and press the text to remove it. iOS should crash.

```js
import React, {useState} from 'react';
import {Text, View} from 'react-native';
import PagerView from 'react-native-pager-view';

const App = () => {
  const [pages, setPages] = useState(5);

  return (
    <PagerView style={{flex: 1}} initialPage={0}>
      {new Array(pages).fill().map((_, i) => (
        <View
          key={i}
          style={{width: '100%', height: '100%', justifyContent: 'center', alignItems: 'center'}}>
          {i !== pages - 1 ? (
            <Text>Please navigate to next page -></Text>
          ) : (
            <Text
              onPress={() => {
                setPages(pages - 1);
              }}>
              Press me to remove this page
            </Text>
          )}
        </View>
      ))}
    </PagerView>
  );
};
```

### PR DESCRIPTION
**Pull request by yinjun322**
Fixes #465

Prevent crash when removing one or many pages at a time

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

### CODE REVIEW

**Comment by troZee** [comment]
@yinjun322 could you resolve the conflicts ?

**Comment by yinjun322** [comment]
> @yinjun322 could you resolve the conflicts ?

done

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.9

**Comment by raymishtech** [comment]
This issue is not fixed yet. The crash is still happening in iOS.

**Pull request merged**
