### PR TITLE
Feat: Page Indicator Props

### PR DESCRIPTION
**Pull request by mssodhi**
# Summary
Closed out https://github.com/callstack/react-native-pager-view/issues/98 and addressed https://github.com/callstack/react-native-pager-view/pull/131
* What is the feature?: We can now set active and inactive dot colors
* How did you implement the solution?
* Passing in a hex string from RN to Native module and using UIColor to set active/inactive colors.
* What areas of the library does it impact?
* Pagination dots

## Test Plan
Tested on both a real device and simulators.
I've enabled dots in the basic example and we can see the dots and custom colors.

[
Screen Shot 2021-06-16 at 11 45 27 AM
](url)

### What are the steps to reproduce (after prerequisites)?
set props of `pageIndicatorProps={{ activeDotColor: 'red', inactiveDotColor: 'blue' }}` and you should see the changes

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [X] I have tested this on a device and a simulator
- [X] I added the documentation in `README.md`
- [X] I updated the typed files (TS and Flow)

### CODE REVIEW

**Comment by paulomcnally** [comment]
@callstack ping

**Comment by mssodhi** [comment]
@troZee any chance we can get your eyes on this? or who would be the best person?

**Comment by brianacowles** [comment]
Any update on this? It would be very useful for the project I'm working on currently.

**Comment by russeg** [comment]
I'm kind of baffled why this is not reviewed and merged. I mean, this probably is one of the very first issues @callstack would have noticed if they actually use this library in their projects. Yeah yeah fork it and make your own fixes ffs.

**Comment by andreialecu** [comment]
The reason this wasn't merged is most likely because it doesn't include an Android implementation.

It's also easy to make your own custom indicator. You don't necessarily need to use the built-in one.

**Comment by pouyarezvani** [comment]
@andreialecu Can you show an example on how to make your own indicator please? I cant seem to be able to access the index

**Comment by mssodhi** [comment]
Closing this due to inactivity by the repository maintainers.

**Comment by chetan51** [comment]
Please reopen, this would be really useful!

**Pull request closed without merging**
