### PR TITLE
fix: pager sometimes does not fill full height

### LINKED ISSUE #523: IOS Bug: border of my component cropped in first render
## Environment
react native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz
react: 17
expo: 44
pager-view: 3.5.9

## Description

Hello guys, I have a problem with the look of the pager view. For the first render, the component border inside pager view was cropped and after I did slide, the component look good and nothing happen. Is anyone have the same problem as me? the component that I used from the native-base library

### LINKED ISSUE #543: Blank screen after rotation or navigation inside of Material Top Tabs (React Navigation)
## Environment

iOS 15.4.1 - iPhone 13 Pro

```
"@react-navigation/material-top-tabs": "^6.2.1",
"@react-navigation/native": "^6.0.10",
"react-native-pager-view": "5.4.15",
"react-native-screens": "^3.13.1",
```

I've tried two different versions of react-native-tab-view since I know that library is in between React Navigation Material Top Tabs and this React Native Pager View:

Latest, last published in 2021:
`"react-native-tab-view": "3.1.1",`

Pull Request that updates Tab View's dependency on Pager View to 5.4.15 from 2 weeks ago:
`"react-native-tab-view": "satya164/react-native-tab-view#1330/head",`

## Description

We use React Navigation (specifically Material Top Tabs) to render multiple, swipeable "pages". We were previously on pager-view 5.4.11 and things were working as expected, but after updating to 5.4.15 (with the intention of pulling in the iOS crash fixes), we started experiencing blank screens after rotating the device. We also will occasionally get blanks screens when navigating directly to a page in the pager-view using `navigation.navigate()`, but it's a bit less frequent that way. I've even seen examples where first load results in a blank screen, but that's even more rare. Rotation is a surefire way to cause the blank screen.

I'm not sure if this issue is related to React Navigation's Material Top Tabs, React Native Tab View, or this Pager View library. Considering the issue comes up only after a Pager View update, I decided to start here first.

## Reproducible Demo
https://user-images.githubusercontent.com/4457848/162533494-0fa26b36-a216-40ec-80a9-98968ab1b18d.mov

This should provide the minimum code necessary to reproduce what we're seeing:

```
import React, { useMemo, useCallback }   from 'react';
import { View, Text }                    from 'react-native';
import { enableScreens }                 from 'react-native-screens';

import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
import { NavigationContainer }           from '@react-navigation/native';

enableScreens(true);

const Tab = createMaterialTopTabNavigator();

function getRandomColor() {
  const letters = '0123456789ABCDEF';
  let color = '#';
  for (let i = 0; i < 6; i++) {
    color += letters[Math.floor(Math.random() * 16)];
  }

  return color;
}

export default function App() {
  const pageData = useMemo(() => {
    const ids = Array.from(Array(30).keys());

    return ids.map(id => {
      return {
        id,
        color: getRandomColor()
      };
    });
  }, []);

  const renderPages = useCallback(() => {
    return pageData.map(page => (
      <Tab.Screen
        key={page.id}
        name={`page-${page.id}`}
      >
        {() => (
          <View style={{
            height: '100%',
            width: '100%',
            backgroundColor: page.color,
            justifyContent: 'center',
            alignItems: 'center'
          }}>
            <Text style={{ fontSize: 48 }}>Page {page.id}</Text>
          </View>
        )}
      </Tab.Screen>
    ));
  }, [ pageData ]);

  return (
    <NavigationContainer>
      <Tab.Navigator
        tabBar={() => null}
        backBehavior="none"
        screenOptions={{
          lazy: true,
          lazyPreloadDistance: 1,
          swipeEnabled: true,
        }}
      >
        { renderPages() }
      </Tab.Navigator>
    </NavigationContainer>
  );
}
```

### PR DESCRIPTION
**Pull request by andreialecu**
Fixes #523
Fixes #543

See https://github.com/callstack/react-native-pager-view/pull/518#issuecomment-1129897222 for more info.

# Summary

### What are the steps to reproduce (after prerequisites)?

See repro at: https://github.com/callstack/react-native-pager-view/pull/518#issuecomment-1129810948

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

### CODE REVIEW

**Comment by troZee** [comment]
@andreialecu thank you for the fix 🎉  ❤️ 
Works as expected

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.21

**Comment by andreialecu** [comment]
@troZee it seems that this PR unfortunately causes a weird issue with the soft keyboard in certain circumstances.

See #566 (includes a repro)

**Comment by cknitt** [comment]
I am still experiencing cut off pager view content after rotation on iPad, even with the latest version 5.4.24.

Commenting out the code under `if (currentVCs.count ...)` as suggested in https://github.com/callstack/react-native-pager-view/issues/543#issuecomment-1093455024 fixes the problem for me.

**Pull request merged**
