### PR TITLE
fix crash with `NSInternalInconsistencyException` on iOS

### PR DESCRIPTION
**Pull request by RishatShamsutdinov**
# Summary

Fix crash with `NSInternalInconsistencyException` on iOS

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ❌     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I updated the typed files (TS and Flow)

### CODE REVIEW

**Comment by RishatShamsutdinov** [comment]
More info about the issue: https://github.com/callstack/react-native-pager-view/issues/507

**Review by troZee — CHANGES_REQUESTED** [review]
@RishatShamsutdinov this solution will create a memory leak, since the reference to the object is strong. 
More explanation here: https://krakendev.io/blog/weak-and-unowned-references-in-swift

**Comment by RishatShamsutdinov** [comment]
The controllers will be relased with the view, it's not memory leak. Just override dealloc method in the view, add breakpoint and check it.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.15

**Comment by ivan-mumtak** [comment]
> https://github.com/callstack/react-native-pager-view/releases/tag/v5.4.15
This bug is still present. I don't have reproducible demo because I'm using react-native-tab-view based on this repo and I have updated pager-view to 5.4.15 but this problem was fixed only partially and everything works fine just 1/3 of time

**Pull request merged**
