### PR TITLE
(@next) fix(android): children views were not recycled

### PR DESCRIPTION
**Pull request by yepMad**
## Summary
Fixes https://github.com/callstack/react-native-pager-view/issues/440

 - This PR overrides the removeAllViews method to ensure that all PagerViewView children are deleted and will not be recycled
 - The removeAllViews function exists in the current version of the project, but does not exist in @next. The motivation was to re-implement it and check if it would work.

### What's required for testing (prerequisites)?
You will need **react-navigation@v6.x**

### What are the steps to reproduce (after prerequisites)?
 1. Insert a PagerView
 2. Insert a button with navigation.navigate(...args) or navigation.replace(...args)
	- In the first case give a "goBack" and normally the application would crash.
	 - In the second case you would face a crash at first.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

 - [X] I have tested this on a device and a simulator
 - [ ] I added the documentation in  `README.md`
 - [ ] I updated the typed files (TS and Flow)

### CODE REVIEW

**Comment by yepMad** [comment]
This is very urgent for me, while this PR is under review I sent a package to NPM. I will delete it when this PR is approved.

https://www.npmjs.com/package/@heymad/react-native-pager-view

**Comment by chakrihacker** [comment]
@yepMad I was not able to crash at least.

Deployed a fix in my app. I will observe for a couple of days on crashlytics

Thanks for the fix 🎉

**Comment by chakrihacker** [comment]
One thing to note, if anyone is trying to use this as patch

You also need to patch libraries that use pager-view like material-top-tabs or bottom tabs with imports

just change the default imports to named imports. everything will work

**Comment by yepMad** [comment]
I had an error when I was in development mode, it usually happened through hot-reload. Reviewing my solution, I realized that it didn't make much sense, although it did work. I believe this new one is more in agreement.

@chakrihacker, maybe you want to update your version. I don't think it's critical, I just played it through hot-reload.

**Comment by troZee** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v6.0.0-rc.1

**Pull request merged**
